name: Install NCBI blast+ toolkit
description: Action for installing NCBI blast+ toolkit

inputs:
  BLAST_VERSION:
    description: "Version of BLAST+ to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Load Cached NCBI blast+ download
      id: blast-cache
      uses: actions/cache@v3
      with:
        path: /usr/bin/ncbi-blast-${{inputs.BLAST_VERSION}}+/bin/
        key: ${{ runner.os }}-${{ hashFiles('**') }}
        
    - name: Install NCBI blast+
      if: steps.blast-cache.outputs.cache-hit != true
      run: |
        curl \
          -o ncbi-blast-${{inputs.BLAST_VERSION}}+-x64-linux.tar.gz \
          "ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/${{inputs.BLAST_VERSION}}/ncbi-blast-${{inputs.BLAST_VERSION}}+-x64-linux.tar.gz"
        sudo tar -xzf \
          ncbi-blast-${{inputs.BLAST_VERSION}}+-x64-linux.tar.gz \
          --strip-components=2 \
          -C /usr/bin/ \
          ncbi-blast-${{inputs.BLAST_VERSION}}+/bin/
      shell: bash
