arguments:
  -reward: 1
  -penalty: -2
  -word_size: 25
  -gapopen: 0
  -gapextend: 2
  -dust: 'no'
  -strand: 'plus'
  -outfmt: '6 qseqid sseqid length mismatch gapopen qstart qend sstart send qseq sseq'
  -subject_besthit: ''
