outfmt6_column_names:
  - query_id
  - subject_id
  - percent_identical
  - alignment_overlap_length
  - n_mismatches
  - n_gapopen
  - query_start
  - query_end
  - subject_start
  - subject_end
  - e_value
  - bit_score