APP:
  i: ENST00000346798.8
  c: chr21
  l: 25880549
  r: 26170770

MAPT:
  i: ENST00000262410.10
  c: chr17
  l: 45894553
  r: 46028334

MAPT_url:
  url: "https://genome.ucsc.edu/cgi-bin/hgc?hgsid=1675269598_JsyRGx7QQs3Shj5LJ6kjXImYEki7&g=htcDnaNearGene&i=ENST00000262410.10&c=chr17&l=45894553&r=46028334&o=knownGene&boolshad.hgSeq.promoter=0&hgSeq.promoterSize=1000&hgSeq.utrExon5=on&boolshad.hgSeq.utrExon5=0&hgSeq.cdsExon=on&boolshad.hgSeq.cdsExon=0&hgSeq.utrExon3=on&boolshad.hgSeq.utrExon3=0&hgSeq.intron=on&boolshad.hgSeq.intron=0&boolshad.hgSeq.downstream=0&hgSeq.downstreamSize=1000&hgSeq.granularity=feature&hgSeq.padding5=0&hgSeq.padding3=0&boolshad.hgSeq.splitCDSUTR=0&hgSeq.casing=exon&boolshad.hgSeq.maskRepeats=0&hgSeq.repMasking=lower&submit=submit"

TARDBP:
  i: ENST00000240185.8
  c: chr1
  l: 11012653
  r: 11025492

TARDBP_url:
  url: "https://genome.ucsc.edu/cgi-bin/hgc?hgsid=1675269598_JsyRGx7QQs3Shj5LJ6kjXImYEki7&g=htcDnaNearGene&i=ENST00000240185.8&c=chr1&l=11012653&r=11025492&o=knownGene&boolshad.hgSeq.promoter=0&hgSeq.promoterSize=1000&hgSeq.utrExon5=on&boolshad.hgSeq.utrExon5=0&hgSeq.cdsExon=on&boolshad.hgSeq.cdsExon=0&hgSeq.utrExon3=on&boolshad.hgSeq.utrExon3=0&hgSeq.intron=on&boolshad.hgSeq.intron=0&boolshad.hgSeq.downstream=0&hgSeq.downstreamSize=1000&hgSeq.granularity=feature&hgSeq.padding5=0&hgSeq.padding3=0&boolshad.hgSeq.splitCDSUTR=0&hgSeq.casing=exon&boolshad.hgSeq.maskRepeats=0&hgSeq.repMasking=lower&submit=submit"

GRN:
  i: ENST00000053867.8
  c: chr17
  l: 44345301
  r: 44353106

GRN_url:
  url: "https://genome.ucsc.edu/cgi-bin/hgc?hgsid=1675280066_5Gaw8iw7fFonTvA3PunN9Lqgzeqs&g=htcDnaNearGene&i=ENST00000053867.8&c=chr17&l=44345301&r=44353106&o=knownGene&boolshad.hgSeq.promoter=0&hgSeq.promoterSize=1000&hgSeq.utrExon5=on&boolshad.hgSeq.utrExon5=0&hgSeq.cdsExon=on&boolshad.hgSeq.cdsExon=0&hgSeq.utrExon3=on&boolshad.hgSeq.utrExon3=0&hgSeq.intron=on&boolshad.hgSeq.intron=0&boolshad.hgSeq.downstream=0&hgSeq.downstreamSize=1000&hgSeq.granularity=feature&hgSeq.padding5=0&hgSeq.padding3=0&boolshad.hgSeq.splitCDSUTR=0&hgSeq.casing=exon&boolshad.hgSeq.maskRepeats=0&hgSeq.repMasking=lower&submit=submit"
  
C9ORF72:
  i: ENST00000380003.8
  c: chr9
  l: 27546545
  r: 27573481

C90RF72_url:
  url: "https://genome.ucsc.edu/cgi-bin/hgc?hgsid=1675280066_5Gaw8iw7fFonTvA3PunN9Lqgzeqs&g=htcDnaNearGene&i=ENST00000380003.8&c=chr9&l=27546545&r=27573481&o=knownGene&boolshad.hgSeq.promoter=0&hgSeq.promoterSize=1000&hgSeq.utrExon5=on&boolshad.hgSeq.utrExon5=0&hgSeq.cdsExon=on&boolshad.hgSeq.cdsExon=0&hgSeq.utrExon3=on&boolshad.hgSeq.utrExon3=0&hgSeq.intron=on&boolshad.hgSeq.intron=0&boolshad.hgSeq.downstream=0&hgSeq.downstreamSize=1000&hgSeq.granularity=feature&hgSeq.padding5=0&hgSeq.padding3=0&boolshad.hgSeq.splitCDSUTR=0&hgSeq.casing=exon&boolshad.hgSeq.maskRepeats=0&hgSeq.repMasking=lower&submit=submit"
