base_url: 'https://genome.ucsc.edu/cgi-bin/hgc'
get_args:
  g: 'htcDnaNearGene'
  o: 'knownGene'
  boolshad.hgSeq.promoter: 0
  boolshad.hgSeq.utrExon5: 0
  boolshad.hgSeq.utrExon3: 0
  boolshad.hgSeq.cdsExon: 0
  boolshad.hgSeq.intron: 0
  boolshad.hgSeq.downstream: 0
  boolshad.hgSeq.splitCDSUTR: 0
  boolshad.hgSeq.maskRepeats: 0
  hgSeq.promoterSize: 1000
  hgSeq.cdsExon: 'on'
  hgSeq.intron: 'on'
  hgSeq.downstreamSize: 1000
  hgSeq.granularity: 'feature'
  hgSeq.padding5: 0
  hgSeq.padding3: 0
  hgSeq.casing: 'exon'
  hgSeq.repMasking: 'lower'
