name: Install bowtie2
description: Action for installing bowtie2

inputs:
  BOWTIE2_VERSION:
    description: "Version to install"
    required: true

runs:
  using: "composite"
  steps:
    - name: Load Cached Download
      id: bowtie2-cache
      uses: actions/cache@v3
      with:
        path: /home/runner/.local/bin/bowtie2*
        key: bowtie2-${{ runner.os }}-${{ inputs.BLAST_VERSION }}
        
    - name: Install bowtie2
      if: steps.bowtie2-cache.outputs.cache-hit != 'true'
      run: |
        micromamba install -c -y bioconda bowtie2=${{ BOWTIE2_VERSION }}
        cp /home/runner/micromamba/bin/bowtie2* /home/runner/.local/bin/
      shell: bash
