name: Docs

on:
  push:

env:
  PYTHON_VERSION: 3.11.2

jobs:

  push-docs:
    name: Build and Publish to Github Pages
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_ref }}
          lfs: True

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install poetry
        run: |
          pip3 install --upgrade poetry
          poetry config virtualenvs.in-project true

      - name: Load Cached Virtualenv
        id: cache
        uses: actions/cache@v2.1.3
        with:
          path: .venv
          key: venv-${{ env.PYTHON_VERSION }}-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/poetry.lock') }}

      - name: Install dependencies and project in dev mode
        if: steps.cache.outputs.cache-hit != true
        run: make install

      - name: Build docs
        run: |
          make doc

      - name: Copy files
        run: |
          cp -r docs/build/${{ github.ref_name }}/* docs/build

      - name: Deploy to Github Pages
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs/build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
