name: Integration Test

on:
  workflow_call:

jobs:

  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_ref }}
          lfs: True

      - uses: nf-core/setup-nextflow@v1
        with:
          version: 23.04.0
          
      - run: nextflow run ${GITHUB_WORKSPACE}/workflows/quality_control.nf