name: Integration Tests

on:
  workflow_call:

env:
  PYTHON_VERSION: 3.11.2
  BLAST_VERSION: 2.14.0

jobs:

  integration-test-qc:
    name: Initial QC
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_ref }}
          lfs: True

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: 23.04.0

      - name: Install NCBI blast+ toolkit
        uses: ./.github/actions/install-blast-plus
        with:
          BLAST_VERSION: ${{ env.BLAST_VERSION }}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}

      - name: Install poetry
        run: |
          pip3 install --upgrade poetry
          poetry config virtualenvs.in-project true

      - name: Load Cached Virtualenv
        id: venv-cache
        uses: actions/cache@v2.1.3
        with:
          path: .venv
          key: venv-${{ env.PYTHON_VERSION }}-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/poetry.lock') }}

      - name: Install dependencies and project in dev mode
        if: steps.venv-cache.outputs.cache-hit != true
        run: make install

      - name: Run Nextflow Integration test
        run: |
          out_dir="${GITHUB_WORKSPACE}/data/"
          mkdir -p $out_dir
          nextflow run ${GITHUB_WORKSPACE}/workflows/integration-test-qc.nf \
            --out_dir $out_dir