name: Unit tests

on:
  workflow_call:

env:
  PYTHON_VERSION: 3.11.2
  BLAST_VERSION: 2.14.0
  USEARCH_VERSION: 11.0.667
  MICROMAMBA_VERSION: 1.4.6
  BOWTIE2_VERSION: 2.5.1

jobs:

  test-pipeline:
    name: Run with code coverage
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git_ref }}
          lfs: True

      - name: Install NCBI blast+ toolkit
        uses: ./.github/actions/install-blast-plus
        with:
          BLAST_VERSION: ${{ env.BLAST_VERSION }}

      - name: Install USEARCH
        uses: ./.github/actions/install-usearch
        with:
          USEARCH_VERSION: ${{ env.USEARCH_VERSION }}
      
      - name: Install micromamba
        uses: ./.github/actions/install-micromamba
        with:
          MICROMAMBA_VERSION: ${{ env.MICROMAMBA_VERSION }}
      
      - name: Install bowtie2
        uses: ./.github/actions/install-bowtie2
        with:
          BOWTIE2_VERSION: ${{ env.BOWTIE2_VERSION }}

      - name: Install and setup Python, Poetry, virtual env
        uses: ./.github/actions/install-python
        with:
          PYTHON_VERSION: ${{ env.PYTHON_VERSION }}

      - name: Run unit tests
        run: |
          make test
        env:
          PY_COLORS: 1

      - name: Report
        run: |
          make report-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
